sed -i "s/title: 'Form left to right: Debra D Key, Andrew J.Key, Jr., and Andrew J. Key III'/title: 'From left to right: Debra D Key, Andrew J.Key, Jr., and Andrew J. Key III'/g" src/app/gallery/page.tsx
# The user wants "make sure each caption is placed under the right photo", this requires manual check if they are misplaced. Wait...
